library(crayon)
library(tidyverse)
library(janitor)
library(cluster)
library(ClusterR)
library(kableExtra)
library(generalizeRdata)
library(viridisLite)
library(viridis)
library(janitor)
library(ggrepel)
library(ggnewscale)
library(lazyeval)


